### ISSUE TITLE
help

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden-SpigotAPI#2]
well, i tried to compile it but im feeling stupid, i got errors at eclipse, is it normal? what i have to do to fix this errors?
![image](https://github.com/diamond-rip/Eden-SpigotAPI/assets/132185379/4fe67c4d-2712-447e-93d1-0fb3ba1f1f6d)

**Comment by serumanooo** [comment]
i have seen that i need to have all these spigot forks to compile it, so i dont think i can compile it

**Comment by GoodestEnglish** [comment]
Yea you can't. This is why I seperate SpigotAPI and Eden
